import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service — Motivv",
  description: "Motivv terms of service.",
};

export default function TermsOfService() {
  return (
    <>
      <nav className="top">
        <Link href="/" className="logo">
          <svg width="24" height="24" viewBox="0 0 40 40" fill="none">
            <circle cx="20" cy="20" r="13" stroke="#5B4FFF" strokeOpacity="0.45" strokeWidth="1.8" />
            <path d="M 7 20 A 13 13 0 0 1 33 20" stroke="#5B4FFF" strokeWidth="3" strokeLinecap="round" />
            <circle cx="33" cy="20" r="3.4" fill="#00D4A8" />
          </svg>
          <span>Motivv</span>
        </Link>
        <div className="links">
          <Link href="/">Home</Link>
          <Link href="/privacy">Privacy</Link>
        </div>
      </nav>

      <main className="legal-page">
        <div className="legal-container">
          <p className="legal-eyebrow">TERMS OF SERVICE</p>
          <h1>Terms of Service</h1>
          <p className="legal-updated">Last updated: 1 May 2026</p>

          <section>
            <h2>Agreement</h2>
            <p>
              By downloading or using Motivv (&ldquo;the App&rdquo;), you agree
              to these Terms of Service. If you do not agree, do not use the
              App.
            </p>
          </section>

          <section>
            <h2>License</h2>
            <p>
              Motivv grants you a personal, non-exclusive, non-transferable
              license to use the App on any Mac signed into the Apple Account
              used to purchase it. This license is granted through the Mac App
              Store and is subject to Apple&apos;s standard terms.
            </p>
          </section>

          <section>
            <h2>One-Time Purchase</h2>
            <p>
              Motivv is available as a one-time purchase. This includes all
              updates within the v1.x release cycle. Future major versions (v2.0
              and beyond) may require a separate purchase, but will be offered at
              a discount to existing customers.
            </p>
          </section>

          <section>
            <h2>Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul>
              <li>Reverse engineer, decompile, or disassemble the App</li>
              <li>Redistribute, sublicense, or resell the App</li>
              <li>Use the App in any way that violates applicable laws</li>
              <li>Remove or modify any proprietary notices in the App</li>
            </ul>
          </section>

          <section>
            <h2>Intellectual Property</h2>
            <p>
              All rights, title, and interest in the App — including its code,
              design, branding, and documentation — remain with the developer.
              Your purchase grants a usage license, not ownership of the
              software.
            </p>
          </section>

          <section>
            <h2>Your Data</h2>
            <p>
              You retain full ownership of any data generated by your use of the
              App. Motivv does not claim any rights to your session data, scores,
              or exported files. See our{" "}
              <Link href="/privacy">Privacy Policy</Link> for details on how
              data is handled.
            </p>
          </section>

          <section>
            <h2>Disclaimer of Warranties</h2>
            <p>
              The App is provided &ldquo;as is&rdquo; without warranties of any
              kind, express or implied. We do not warrant that the App will be
              uninterrupted, error-free, or that it will meet your specific
              requirements. Work rate scores are estimates based on app usage
              patterns and should not be treated as precise measurements.
            </p>
          </section>

          <section>
            <h2>Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, the developer shall not be
              liable for any indirect, incidental, special, or consequential
              damages arising from your use of the App, including but not limited
              to loss of data, loss of profits, or business interruption.
            </p>
          </section>

          <section>
            <h2>Refunds</h2>
            <p>
              Refunds are handled through the Mac App Store in accordance with
              Apple&apos;s refund policy. The developer does not process refunds
              directly.
            </p>
          </section>

          <section>
            <h2>Changes to These Terms</h2>
            <p>
              We may update these terms from time to time. Continued use of the
              App after changes constitutes acceptance of the revised terms.
              Material changes will be communicated through the App or on this
              page.
            </p>
          </section>

          <section>
            <h2>Governing Law</h2>
            <p>
              These terms are governed by the laws of England and Wales. Any
              disputes shall be resolved in the courts of England and Wales.
            </p>
          </section>

          <section>
            <h2>Contact</h2>
            <p>
              For questions about these terms, contact us at{" "}
              <a href="mailto:hello@motivv.app">hello@motivv.app</a>.
            </p>
          </section>
        </div>
      </main>

      <footer>
        <div className="left">
          <svg width="18" height="18" viewBox="0 0 40 40" fill="none">
            <circle cx="20" cy="20" r="13" stroke="#5B4FFF" strokeOpacity="0.45" strokeWidth="2.2" />
            <path d="M 7 20 A 13 13 0 0 1 33 20" stroke="#5B4FFF" strokeWidth="3.5" strokeLinecap="round" />
            <circle cx="33" cy="20" r="3.4" fill="#00D4A8" />
          </svg>
          <span>Motivv &middot; v1.0 &middot; &copy; 2026 Tade</span>
        </div>
        <div className="right">Made with care &middot; Shipped with patience</div>
      </footer>
    </>
  );
}
